[package]
name = "bds_listd_bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
once_cell = "1.21.3"
serde = {version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
regex = "1.11.1"
